### ISSUE TITLE
Update from v3.1.2.1 to v3.3.1.1

### ISSUE THREAD

**Issue by qayshp** [monkeysintown/jgraphx#1]
Would you be able to update the build to [v3.3.1.1](https://github.com/jgraph/jgraphx/releases/tag/v3.3.1.1)?

**Comment by vidakovic** [comment]
I've just published version 3.3.1.1 on Bintray and Maven Central. Will take a bit until it's visible on Maven Central. If you point your Maven repository to Bintray then you should see the new version immediately.

**Comment by qayshp** [comment]
Thank you!
